### ISSUE TITLE
'Qubit' object has no attribute 'classifiers_hpars' Error

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#586]
Hi All, I'm trying to run the follwing two actions on qw5q_gold_qublox:
```yaml
platform: qw5q_gold_qblox
qubits: [0, 1, 2, 3, 4]
format: csv
actions:
  - id: single shot classification
    priority: 0
    next: chevron
    operation: single_shot_classification
    parameters:
      nshots: 4096

  - id: chevron
    operation: chevron
    priority: 10
    qubits: [[0, 2], [1, 2], [2, 3], [2, 4]]
    parameters:
      amplitude_min: -1
      amplitude_max: 1
      amplitude_step: 0.02
      duration_min: 1
      duration_max: 60
      duration_step: 1
      nshots: 1000
```
I'm using main on all three repositories (qibocal, qibolab and qibolab_qrc_platforms)
I get the following error
```
Traceback (most recent call last):
  File "/nfs/users/alvaro.orgaz/.envs/november/bin/qq", line 6, in <module>
    sys.exit(command())
  File "/nfs/users/alvaro.orgaz/.envs/november/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/users/alvaro.orgaz/.envs/november/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/nfs/users/alvaro.orgaz/.envs/november/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nfs/users/alvaro.orgaz/.envs/november/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/users/alvaro.orgaz/.envs/november/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/users/alvaro.orgaz/qibocal/src/qibocal/cli/_base.py", line 53, in auto
    autocalibrate(card, folder, force, update)
  File "/nfs/users/alvaro.orgaz/qibocal/src/qibocal/cli/autocalibration.py", line 61, in autocalibrate
    for task_uid in executor.run(mode=ExecutionMode.autocalibration):
  File "/nfs/users/alvaro.orgaz/qibocal/src/qibocal/auto/execute.py", line 136, in run
    completed = task.run(
  File "/nfs/users/alvaro.orgaz/qibocal/src/qibocal/auto/task.py", line 146, in run
    completed.data, completed.data_time = operation.acquisition(
  File "/nfs/users/alvaro.orgaz/qibocal/src/qibocal/auto/operation.py", line 41, in wrapper
    out = func(*args, **kwds)
  File "/nfs/users/alvaro.orgaz/qibocal/src/qibocal/protocols/characterization/classification.py", line 186, in _acquisition
    hpars[qubit] = qubits[qubit].classifiers_hpars
AttributeError: 'Qubit' object has no attribute 'classifiers_hpars'
```

**Comment by Edoardo-Pedicillo** [comment]
Thank @aorgazf to report the bug

**Comment by aorgazf** [comment]
Thanks!
