### ISSUE TITLE
Qibocal try to assign attenuation to an instrument that has not

### ISSUE THREAD

**Issue by JavierSerranoGarcia** [qiboteam/qibocal#738]
I am creating a new platform to test a new FPGA board. Trying to run this routine

```
platform: TII2q3_HTG-ZRF8
targets: [1,2]
format: csv
actions:


  - id: resonator_spectroscopy high power
    priority: 0
    operation: resonator_spectroscopy
    # main: resonator punchout
    parameters:
      freq_width: 10_000_000
      freq_step: 100_000
      amplitude: 0.4
      power_level: high
      nshots: 1024
      relaxation_time: 0
```

I am getting a weird error complaining about attenuation when the platform has no attenuation parameter

```
[Qibo 0.2.3|INFO|2024-02-29 16:24:08]: Loading platform /home/users/javier.serrano/qiboDev/qibolab_platforms_qrc/TII2q3_HTG-ZRF8
[Qibo 0.2.3|INFO|2024-02-29 16:24:08]: Using qibolab (/home/users/javier.serrano/qiboDev/qibolab_platforms_qrc/TII2q3_HTG-ZRF8) backend on /CPU:0
[Qibo 0.2.3|INFO|2024-02-29 16:24:08]: Loading platform /home/users/javier.serrano/qiboDev/qibolab_platforms_qrc/TII2q3_HTG-ZRF8
[Qibo 0.2.3|INFO|2024-02-29 16:24:08]: Using qibolab (/home/users/javier.serrano/qiboDev/qibolab_platforms_qrc/TII2q3_HTG-ZRF8) backend on /CPU:0
[38;20m[Qibocal 0.0.8|INFO|2024-02-29 16:24:08]: Creating directory reports/202402_res_spec_high.[0m
[Qibo 0.2.3|INFO|2024-02-29 16:24:08]: Connecting to instrument <qibolab.instruments.rfsoc.driver.RFSoC object at 0x7fc9a0256b00>.
[Qibo 0.2.3|INFO|2024-02-29 16:24:08]: Connecting to instrument <qibolab.instruments.rohde_schwarz.SGS100A object at 0x7fc9a0255c90>.
[38;20m[Qibocal 0.0.8|INFO|2024-02-29 16:24:09]: Executing mode autocalibration on resonator_spectroscopy high power iteration 0.[0m
Connected to: Rohde&Schwarz SGS100A (serial:1416.0505k02/114167, firmware:4.2.76.0-4.30.046.295) in 0.20s
Traceback (most recent call last):
  File "/nfs/users/javier.serrano/qiboDev/env/bin/qq", line 8, in <module>
    sys.exit(command())
  File "/nfs/users/javier.serrano/qiboDev/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/users/javier.serrano/qiboDev/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/nfs/users/javier.serrano/qiboDev/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nfs/users/javier.serrano/qiboDev/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/users/javier.serrano/qiboDev/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/users/javier.serrano/qiboDev/qibocal/src/qibocal/cli/_base.py", line 72, in auto
    autocalibrate(runcard, folder, force, update)
  File "/nfs/users/javier.serrano/qiboDev/qibocal/src/qibocal/cli/autocalibration.py", line 56, in autocalibrate
    for _ in executor.run(mode=ExecutionMode.autocalibration):
  File "/nfs/users/javier.serrano/qiboDev/qibocal/src/qibocal/auto/execute.py", line 142, in run
    completed = task.run(
  File "/nfs/users/javier.serrano/qiboDev/qibocal/src/qibocal/auto/task.py", line 124, in run
    completed.data, completed.data_time = operation.acquisition(
  File "/nfs/users/javier.serrano/qiboDev/qibocal/src/qibocal/auto/operation.py", line 41, in wrapper
    out = func(*args, **kwds)
  File "/nfs/users/javier.serrano/qiboDev/qibocal/src/qibocal/protocols/characterization/resonator_spectroscopy.py", line 135, in _acquisition
    attenuation = platform.qubits[qubit].readout.attenuation
KeyError: 1
```
In a branch TII2q3_HTG-ZRF8 in qibolab_platforms_qrc the platform and the runcard can be found

**Comment by andrea-pasquale** [comment]
There should be an error either in `qibosoq` or in `qibolab` in the rfsoc driver.
