### ISSUE TITLE
Script crashing if unsuccessful fitting 

### ISSUE THREAD

**Issue by maxhant** [qiboteam/qibocal#79]
Hi @andrea-pasquale, 
From one routine to the next, if the fitting is unsuccessful, the routine will crash because of the saving of parameters in the runcard. 

https://github.com/qiboteam/qcvv/blob/7e35bf50a8602dddfca94454b9d51db8726a5329/src/qcvv/cli/builders.py#L159

Error bellow:
`Traceback (most recent call last):
  File "/home/users/maxime.hantute/.conda/envs/qcvv_fix/bin/qq", line 8, in <module>
    sys.exit(command())
  File "/home/users/maxime.hantute/.conda/envs/qcvv_fix/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/users/maxime.hantute/.conda/envs/qcvv_fix/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/users/maxime.hantute/.conda/envs/qcvv_fix/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/users/maxime.hantute/.conda/envs/qcvv_fix/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/users/maxime.hantute/qcvv/src/qcvv/cli/_base.py", line 52, in command
    action_builder.execute()
  File "/nfs/users/maxime.hantute/qcvv/src/qcvv/cli/builders.py", line 130, in execute
    self._execute_single_action(routine, args, path)
  File "/nfs/users/maxime.hantute/qcvv/src/qcvv/cli/builders.py", line 145, in _execute_single_action
    self.update_platform_runcard(qubit, routine.__name__)
  File "/nfs/users/maxime.hantute/qcvv/src/qcvv/cli/builders.py", line 160, in update_platform_runcard
    settings["characterization"]["single_qubit"][qubit][param] = int(
ValueError: cannot convert float NaN to integer`

This happened while running a Rabi. 

Btw, another issue would be that both the phase and MSR should be fitted. So one needs to save the parameter that best fits its corresponding data. 

Let me know if you need an example to run, but it won't be easy for me to provide.

**Comment by scarrazza** [comment]
Shall we close this issue?Does this

**Comment by andrea-pasquale** [comment]
Yes, we can close it. I think that in the autocalibration this should not happen anymore.
